# Generated by Django 2.1.2 on 2018-12-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان آغاز')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
            ],
            options={
                'verbose_name': 'رابطه دوستی',
                'verbose_name_plural': 'روابط دوستی',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='تعداد انتشار')),
                ('first_time', models.DateTimeField(blank=True, null=True, verbose_name='اولین انتشار')),
                ('last_time', models.DateTimeField(blank=True, null=True, verbose_name='آخرین انتشار')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='عمق')),
            ],
            options={
                'verbose_name': 'محتوای جریان\u200cساز',
                'verbose_name_plural': 'محتواهای جریان\u200cساز',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('url', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PostMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Meme', verbose_name='محتوای جریان\u200cساز')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Post', verbose_name='پست')),
            ],
        ),
        migrations.CreateModel(
            name='Reshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان')),
                ('ref_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پست مرجع')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='crud.Post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'بازنشر',
                'verbose_name_plural': 'بازنشرها',
            },
        ),
        migrations.CreateModel(
            name='SocialNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('icon', models.CharField(max_length=200, verbose_name='نشان')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری')),
                ('friends_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد دوستان')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان آغاز')),
                ('exit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='عکس آواتار')),
                ('social_net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.SocialNet', verbose_name='شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب\u200cهای کاربری',
            },
        ),
        migrations.AddField(
            model_name='reshare',
            name='ref_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_reshares', to='crud.UserAccount', verbose_name='کاربر مرجع'),
        ),
        migrations.AddField(
            model_name='reshare',
            name='reshared_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crud.Post', verbose_name='پست مرجع'),
        ),
        migrations.AddField(
            model_name='reshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_reshares', to='crud.UserAccount', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.UserAccount', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crud.UserAccount', verbose_name='کاربر 1'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crud.UserAccount', verbose_name='کاربر 2'),
        ),
    ]
