# Generated by Django 2.1.1 on 2018-12-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reshare',
            name='ref_datetime',
        ),
        migrations.RemoveField(
            model_name='reshare',
            name='ref_user',
        ),
        migrations.RemoveField(
            model_name='reshare',
            name='user',
        ),
    ]
