# Generated by Django 2.1.1 on 2019-01-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20181226_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='socialnet',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exit_datetime',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='start_datetime',
        ),
    ]
