# Generated by Django 2.1.1 on 2019-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190110_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='reshare',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان'),
        ),
    ]
